# Name of deployment. Should be global unique
# service_name: "be-notification"
# Docker image of application. May be ignored on production deployment.
# image: "registry.hub.docker.com/library/be-be-notification:bbd7e9b0a4512e8b49563279280f1e74eb47b700"
# Number of instances. Default: 2
count: 2
canary: 1
# Auto revert to previous version if error occur. Default: false
auto_revert: true
# Maximum update instances at a time. Default: 1
max_parallel: 1
# Application
# app_files: # Use to copy local file from repo to app. In application will reallocated at /local/<destination>
#   - src: deployment/config.toml
#     destination: config.toml # => /local/config.toml
#     env: false # Is this file will use as environment variables. Default: false.
#   - src: deployment/env
#     destination: .env # => /local/.env
#     env: true
# entrypoint:
#   - /app
#   - start
#   - --config=${CONFIG_FILE}
# directories: # List of volumes on node/server that app will use. Default: []
#   - /data/logs/be-notification
# Register services into consul
# services:
#   - name: be-notification
#     port: grpc
#     prometheus: true # Dedicated that service will have prometheus endpoint.
#     prometheus_port: metrics # Defined which port prometheus to scape. Default: metrics
#     tags: # Optional.
#       - grpc
#  - name: be-notification-http
#    port: http
#    tags:
#      - traefik.enable=true
#      - traefik.http.routers.api-merchant.rule=PathPrefix(`/v1/merchant`)
#      - traefik.http.routers.api-merchant.entrypoints=http
# Resources
resources: # Required. At least one of below attributes must be defined
  mbits: "1" # Net speed. Default: 1
  # cpu: "20" # MHz. Default: 100
  # memory: "50" #MB. Default: 300

# Add host
# extra_hosts:
#   - "consul-dev.liemdeptrai:10.30.83.2"
# Define constraints
# constraints:
#   - key: "acl_enabled"
#     operator: "="
#     value: "True"
dns_servers: 
  - "10.30.83.86"
  - "10.30.83.87"
dns_search_domains: ["qtsc.local.zpw.dev"]